export const TODO_LIST_ACTIONS = {
  CREATE_NEW_TASK: 'CREATE_NEW_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  REMOVE_ALL_TASKS: 'REMOVE_ALL_TASKS',
  SET_ACTIVE_TASK: 'SET_ACTIVE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  SET_COUNTER_STARTED: 'SET_COUNTER_STARTED',
}
